requiments: Require scikit-learn 1.2+ in dev deps
Example code uses recent plotting tools from there

Fixes exceptions like

	ImportError: cannot import name 'DecisionBoundaryDisplay' from 'sklearn.inspection'