bayes: Fix compatibility with sklearn 1.2.0+
The sigma_ attribute was deprecated in 1.0 and removed in 1.2

Fixes exception like
AttributeError: 'GaussianNB' object has no attribute 'sigma_'