requiremens: Pin numpy < 1.24
Recently released numpy 1.24 causes an import problem with numba

    from numba.np.ufunc import _internal
    SystemError: initialization of _internal failed without raising an exception

References https://github.com/numba/numba/issues/8615